-- Registro de mantenimiento: backups diarios a S3 y latidos para que Supabase
-- (plan gratis) no pause el proyecto tras 7 días sin actividad.
--
-- RLS habilitado y sin políticas: sólo la service role (workflow de backup vía
-- REST) y el dueño de la tabla (Prisma) leen y escriben. anon/authenticated no.
--
-- Aditiva: una tabla y una función nuevas, sin tocar nada existente.

CREATE TABLE IF NOT EXISTS public.maintenance_runs (
    "id"         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
    "kind"       TEXT NOT NULL CHECK ("kind" IN ('backup', 'keepalive')),
    "ok"         BOOLEAN NOT NULL,
    "detail"     JSONB,

    CONSTRAINT "maintenance_runs_pkey" PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS "maintenance_runs_kind_created_at_idx"
    ON public.maintenance_runs ("kind", "created_at" DESC);

ALTER TABLE public.maintenance_runs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.maintenance_runs FROM anon, authenticated;

-- Uso de espacio contra los topes del plan gratis (base 500 MB, archivos 1 GB).
-- security definer para poder leer storage.objects; search_path vacío para que
-- no se pueda secuestrar con objetos de otro schema.
CREATE OR REPLACE FUNCTION public.storage_usage()
RETURNS TABLE (db_bytes BIGINT, storage_bytes BIGINT, storage_objects BIGINT)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = ''
AS $$
    SELECT
        pg_catalog.pg_database_size(pg_catalog.current_database())::BIGINT,
        COALESCE(SUM((o.metadata->>'size')::BIGINT), 0)::BIGINT,
        COUNT(*)::BIGINT
    FROM storage.objects o
$$;

REVOKE ALL ON FUNCTION public.storage_usage() FROM public, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.storage_usage() TO service_role;
